govuk-one-login/txma-ticf-integration

.github/workflows/pipeline.yml

The GH hosted agents have Yarn 1 installed by default. Since the default node version is 16.16, we can run `corepack enable` in order to use Yarn 3 as the package manager. Previously, Yarn install was installing node modules instead of using the checked in dependencies we have.

Enable corepack in pipeline to install Yarn 3

---

.github/workflows/pipeline.yaml
.prettierignore
template.yaml

- Added a pipeline that can deploy to AWS
- Deployment job re-uses the build artifact from the validation job
- Includes some secrets that have been added to this repos config
- Added SAM template to Prettier ignore file as when conditions are added it looks like it was breaking the layout
- Updated SAM template with Code Signing config - the values for this are provided by the Codebuild pipeline that gets triggered when this Deploy job uploads the SAM package to AWS. We don't so `sam deploy` in GH Actions, instead the final is a `sam package` that uploads to S3, Secure Pipelines handles the rest.

Add deployment pipeline

---

.husky/pre-commit
README.md

Since Checkov is running in the deploy pipeline, but not the build pipeline, have added it as a pre-commit hook to help catch things before they get merged and the deployment subsequently fails.
We may want to consider putting this in the Build pipeline in future, but worth mentioning that this isn't a guarantee that the deployment won't fail, since SAM creates resources behind the scenes that Checkov can't scan.

Add checkov as pre-commit hook if template.yaml file changed

---

template.yaml

Alias name should start with "alias", according to AWS documentation

Correct KMS alias name

---

template.yaml

- added the required KMS key policy that the `initiateAthenaQuery` lambda required to decrypt queue data
- upon 5 attempts to deal with the queue data, the queue entry will be sent to the DLQ

Feature/tt2 62  sqs between retrieval and athena

---

template.yaml

There is a bug in AWS SAM where if you do not speficy the OpenAPI version, then an additional stage named 'Stage' is created along with the stage name you specify. Have added this as a global so that all future APIs will not include this extra duplicate.

Add openapi version to API to remove duplicate default 'Stage'

---

template.yaml

Added explicit log groups for each lambda function so we can set their retention policy. The SAM generated log groups set the retention policy to unlimited, which is not good for keeping costs under control!
Additionally, have given the lambda functions explicit names, as we need to use the name in the Log Group resource.

Lambda Cloudwatch logs expiry

---

template.yaml

The logs for the EmptyS3Buckets function were sometimes created after the custom resource. This meant that the function would trigger (to decide if it should act on CloudFormation events - in this case Creates instead of Deletes so no action is taken) before the log group is configured, and create the log group itself. This had 2 side effects:
1. The log group would exist with the default retention, so it would never expire or delete with the stack
2. Sometimes CloudFormation would report the log group already exists and fail the deployment
Have added a DependsOn to the Custom resource so it doesn't exist until both the lambda and log group have finished creating.

Add depends on for custom resource in template

---

.github/workflows/build-test-package.yaml

Manually running deployments was not working as every step was being skipped. This includes the event `workflow_dispatch` (which represents manual deployments) in the conditions for the relevant jobs.

Add workflow_dispatch to relevant conditions

---

.github/workflows/build-test-package.yaml
.yarn/sdks/typescript/package.json
samconfig.toml
template.yaml

- Start using the environments parameter in resource naming
- Remove all hardcoded 'sandbox' references from template
- Update config file as we only care about dev for deployments and build for validation - the other environments are handled by the AWS pipelines

Update to use environments in template file

---

README.md
integration-tests/types/environmentVar.ts
integration-tests/utils/aws/retrieveSecureDownloadDbRecord.ts

This PR adds a function to the integration test area of the codebase that lets us query the secure download database by zendeskId.
The code needs the new environment variable SECURE_DOWNLOAD_DYNAMODB_TABLE to be set

During integration test, allow retrieval of secure download record

---

src/lambdas/initiateAthenaQuery/createQuerySql.spec.ts
src/lambdas/initiateAthenaQuery/createQuerySql.ts

An update to the athena query SQL generation to handle:
- uppercase letters in dataPaths (these need to be put into lower case for athena queries, even if the item in s3 has an upper or camel case key)
- formatting the results column name in the event that the dataPath includes an index for an array ( '[' and ']' are not permitted characters for a column name, and the regex also pulls out the numerals, thus a path of 'restricted.address[0].uprn' leads to a results column of 'address_uprn'
- tests expanded to cover these cases

Handle irregular dataPaths

---

.github/workflows/build-test-package.yaml
.github/workflows/delete-feature-branch.yaml
samconfig.toml

* The Check Yarn cache job takes approx the same time to complete as the validate/run tests job. Since they run in parallel, decided it was better to run this job on all pushes instead of just PRs. This lets us remove the PR trigger and just have push triggers and avoid duplicate jobs running when PRs are opened.
* This lets us clean up the trigger conditions on other jobs
* Removed the `build` configuration from `samconfig.toml` as this was never used
* Removed the Dev S3 bucket from the deploy feature branch job. Instead we pass a `--resolve-s3` flag, which will create a SAM managed S3 bucket for us, and use an existing one if it already exists

Cleanup pipeline triggers and job conditions

---

src/lambdas/initiateAthenaQuery/createQuerySql.spec.ts
src/lambdas/initiateAthenaQuery/createQuerySql.ts

Adding string casing around the ID execution parameter to cater for cases where IDs are made up entirely of numerals.

Add string casing around execution params

---

template.yaml

Added some policies that should only deploy when we have a TestRoleArn parameter passed to the template. These policies are for the S3 buckets and the SQS queue we use. Please let me know if any are missing!
Things to note:
* The audit bucket lives in another stack and is deployed by the TxMA team's repo - this means we are deploying a policy to the bucket they provide us. Shouldn't really be a problem since this will only ever deploy in the build and staging accounts, where we will have just the 1 bucket.
* The SQS queue is encrypted, and according to the AWS docs the policy to allow decrypt goes on the Key. We already allow this.

Add resource based policies for integration tests

---

src/lambdas/initiateDataRequest/validateZendeskRequest.spec.ts
src/lambdas/initiateDataRequest/validateZendeskRequest.ts
src/lambdas/initiateDataRequest/zendeskTicketDiffersFromRequest.spec.ts
src/lambdas/initiateDataRequest/zendeskTicketDiffersFromRequest.ts

Production Zendesk is set up using a prefix for identifier types, so we need to handle this

Accept a prefix of pii_identifier_ for identifier types

---

integration-tests/tests/utils/aws/cloudWatchGetLogs.ts

The tests currently search the last 5 log streams for logs, have increased this to 15 in case we're seeing some flakiness due to having a low number to search through.

Increase limit for number of log streams searched in tests

---

integration-tests/tests/utils/queryResults/downloadAndParseResults.ts

Logging out some data from the csv, and the S3 URL. We assert on these things, so I don't think we need these logs?

Remove more noisy logs

---

.github/workflows/build-test-package.yaml

Because of an error introduced by the AWS CLI team, SAM validate doesn't work.
There's a workaround suggested in this bug report
https://github.com/aws/aws-sam-cli/issues/4527
https://github.com/aws/aws-sam-cli/issues/4527#issuecomment-1369095544
which we've followed and it seems to work!

Update to fix issue with SAM validate

---

src/constants/zendeskConstants.ts
src/lambdas/initiateDataRequest/validateZendeskRequest.spec.ts
src/lambdas/initiateDataRequest/validateZendeskRequest.ts
src/lambdas/initiateDataRequest/zendeskTicketDiffersFromRequest.spec.ts
src/lambdas/initiateDataRequest/zendeskTicketDiffersFromRequest.ts
src/utils/helpers.ts
src/utils/tests/testConstants.ts
tests/e2e-tests/test-suites/endToEndFlow.spec.ts
tests/shared-test-code/constants/zendeskParameters.ts
tests/shared-test-code/utils/zendesk/generateZendeskTicketData.ts

We discovered that production Zendesk had to be set up to include a prefix for all PII types (because they appear as generic tags on a ticket, and the administrator didn't want this getting confusing)

Tolerate pii_requested_ as a prefix for PII types

---

tests/shared-test-code/utils/aws/dynamoDB.ts

This PR fixes the integration test failure that arose from PII types including a prefix in Zendesk

Fix the integration tests following PII type change

---

.github/dependabot.yaml

Have dependabot ignore AWS SDK updates as these are quite noisy, and sometime they break our builds.

Ignore AWS SDK updates

---

tests/shared-test-code/utils/aws/dynamoDB.ts

This tweak sends the Zendesk ID over to the DynamoOperations lambda for the PutCommand. This is present in both the other operations (Get, Delete) but was missed for Put. Changing this so that the [if function in the lambda](https://github.com/alphagov/di-txma-infra/blob/c3cd3733b25e69e045d53931c313e98c6cc4cc89/dev-tools/src/lambdas/dynamoOperations/handler.ts#L25) can append the Zendesk ID to its logs in the case of a Put invocation.

added zendeskId to putDynamo lambda invoke

---

tests/shared-test-code/utils/aws/s3WaitForFile.ts
tests/shared-test-code/utils/aws/setupAuditSourceTestData.ts

The test setup for encrypted data was hard-coded to dev. 
There was also some confusing test setup that silently failed to notice that a required file wasn't there, so I've made it noisy now so we can easily see what's going on.

Fix mistake in encrypted data setup for test

---

template.yaml

The integration tests failed to run in the pipeline because the test role hadn't been given permission to read from the permanent message batch bucket (which is needed when we're in encrypted mode).

Allow test  role to read from permanent audit bucket

---

template.yaml

Since moving the KMS encryption key to its own stack, the SSM parameter for it changed

Use new SSM param for KMS encryption key

---

open-api-specification.yaml
package.json
template.yaml

- An Open API spec which includes the original `/zendesk-webhook` endpoint 
- Four new endpoints :
- `/security.txt`,  `/.well-known/security.txt`, which redirect to https://vdp.cabinetoffice.gov.uk/.well-known/security.txt
- `/thanks.txt` and `/.well-known/thanks.txt`, which redirect to https://vdp.cabinetoffice.gov.uk/.well-known/thanks.txt

TT2-738-add-security-txt-redirect-to-sal

---

template.yaml

Was going to write a script to add messages to the "InitiateDataRequestQueue" for manual audit data requests. However, noticed the queues in this repo don't have predictable names. So have added the `QueueName` property to all SQS queues.

Give SQS queues predictable names

---

tests/shared-test-code/utils/aws/cloudWatchGetLogs.ts

The integration tests were failing when run against a freshly created stack (i.e. a feature stack in dev).
This was because they didn't cope with the situation of no log streams which we get right at the start before a Lambda has run for the first time.
This PR changes things so we simply return empty results to the caller if we attempt to search with an empty log stream list

Check for empty log streams list in tests

---

template.yaml

- **Ticket Number**: #[1545](https://govukverify.atlassian.net/browse/TT2-1554) :ticket:
after updating API key with a new key, the test container was unable to obtain secret due to custom kms key used by secrets manager. looking at event replay, its secrets are
1. in the config repo
2. doesnt use a custom KMS key 
so i've updated the secret to not use a custom kms key, this should allow the pipeline to run
- remove custom kms key for test secrets and add a checkov ignore

TT2-1554 - remove custom kms encrpytion of test secrets manager

---

src/lambdas/sendQueryResultsNotification/handler.ts

tiny pr that re-orders the logging statement so we can map the athena query to a zendesk ticket

map-athena-id-to-zendesk-in-logs

---

.gitignore
template.yaml

Ticket Number: [TT2-1977](https://govukverify.atlassian.net/browse/TT2-1977)  🎫
Documentation Link(s): [Confluence](https://govukverify.atlassian.net/wiki/spaces/TMA/pages/4295360647/Lambdas+across+TxMA#Repo%3A-txma-ticf-integration) :books:
Add alarms to lambdas as outlined in Confluence link. A separate PR will be needed to complete 1977 by adding canary deployments once we are happy with the alarms
- Add IaC code for alarms
- Confluence link will need to be updated when this is merged
[TT2-1977]: https://govukverify.atlassian.net/browse/TT2-1977?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

TT2-1977 Add alarms

---

template.yaml

Ticket Number: [TT2-1977](https://govukverify.atlassian.net/browse/TT2-1977)  🎫
Documentation Link(s): [Confluence](https://govukverify.atlassian.net/wiki/spaces/TMA/pages/4295360647/Lambdas+across+TxMA#Repo%3A-txma-ticf-integration) :books:
Add canary deployments to lambdas as outlined in Confluence link
- Add IaC code for canary deployments
- Confluence link will need to be updated when this is merged
[TT2-1977]: https://govukverify.atlassian.net/browse/TT2-1977?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

TT2-1977 Add canary deployments

---

README.md
template.yaml

make decrypts way faster by increasing max executions. its below 5% of global account limit so plenty of executions left for firehose

bump executions

---

scripts/setupDevStackSecrets.ts
src/lambdas/initiateAthenaQuery/startQueryExecution.ts
src/sharedServices/bulkJobs/describeBatchJob.ts
src/sharedServices/bulkJobs/getS3BatchJobTags.ts
src/sharedServices/bulkJobs/startGlacierRestore.ts
src/sharedServices/bulkJobs/startTransferToAnalysisBucket.ts
src/sharedServices/bulkJobs/writeJobManifestFileToJobBucket.ts
src/sharedServices/dynamoDB/dynamoDBClient.ts
src/sharedServices/dynamoDB/dynamoDBGet.ts
src/sharedServices/dynamoDB/dynamoDBPut.ts
src/sharedServices/dynamoDB/dynamoDBUpdate.ts
src/sharedServices/queue/sendSqsMessage.ts
src/sharedServices/s3/copyS3Object.ts
src/sharedServices/s3/getS3ObjectAsStream.ts
src/sharedServices/s3/listS3Files.ts
src/sharedServices/s3/putS3Object.ts
src/sharedServices/s3/readS3DataToString.ts
src/sharedServices/secrets/retrieveSecrets.ts
src/utils/awsSdkClients.ts

- **Ticket Number**: #[TT2-1922] :ticket:
Refactor to instantiate a single S3 client and a single SQS client, and use them everywhere, rather than potentially creating a new client per call to the lambda.
Integration tests in a feature branch in the `di-txma-audit-dev` account fail, but they fail there for the main branch too.
[TT2-1922]: https://govukverify.atlassian.net/browse/TT2-1922?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

TT2-1922 Externalise AWS SDK calls

---

.github/pull_request_template.md
README.md
package.json

https://govukverify.atlassian.net/browse/DPT-1189
migration from yarn to npm changed how cli tool is invoked, this pr updates the process and docs

update cli tool and docs
