govuk-one-login/txma-ticf-integration

.prettierignore
scripts/assumeRole.sh

Adds a script we can use with the AWS CLI to assume a role in another AWS account.

Add an assume role script

---

.github/workflows/pipeline.yml
.github/workflows/pre-merge.yaml
.prettierignore
samconfig.toml

- Added test, build, and SAM template validate steps
- Assume SAM Validate role in AWS

Build pipeline integrated with AWS

---

src/handlers/initiateDataRequest.ts
src/types/validatedDataRequestParamsResult.ts

We need the validation function to return a message indicating what was invalid

Add message to validation

---

.husky/pre-commit
template.yaml

- Fix reference to API Gateway Access logs
- Update some naming
- Make checkov hook quieter

SAM template updates

---

template.yaml

- Policy so lambda function can list S3 objects
- Adjusted timeout value as our function will be running longer than the default of 3 seconds

Add permission to list S3 objects

---

src/services/retrieveZendeskApiSecrets.spec.ts
src/services/retrieveZendeskApiSecrets.ts
src/services/updateZendeskTicket.spec.ts
src/services/updateZendeskTicket.ts
src/types/zendeskApiSecrets.ts
src/utils/tests/setup/testEnvVars.ts
template.yaml

ZendeskHostName is now accessed from secretsManager

replaced ZendeskHostName with a secret

---

template.yaml

Small PR to add to SAM template to create an Athena query results bucket in s3

add query results bucket to template

---

.github/workflows/pipeline.yaml
samconfig.toml
template.yaml

Since we are using a dev/sandbox account, we are able to deploy to this from our local machines via sam deploy. To make this more efficient, have added a role that GH can use to deploy and have set up the pipeline to deploy feature branches automatically, and delete the provisioned resources when the branch is deleted.
Some important things to note:
* We have S3 buckets in our SAM template so these will not delete unless they are emptied first - will address this in a separate PR
* S3 buckets can be a maximum of 64 characters in length and in our template these are set to be `{stack_name}-{bucket_name}`. In this PR, I have limited the stack name for feature branches to 32 chars, meaning we have a remaining 32 chars to describe the bucket. I'm hoping this is ok, but we can change this as …

Deploy feature branches in pipeline

---

template.yaml

Add WAF association

---

infrastructure/athena.yaml

Add columns to the athena table to allow searching by journey_id, session_id and user_id

add id columns to athena table

---

template.yaml

* Add a custom domain to API Gateway for build environment and upwards
* Improve access logs (copied this from IPV Core team so it's at least in the same format as another team)
* Turn off the AWS URL for build environment and upwards

Add custom domain to API Gateway

---

template.yaml

- Adds a parameter for TestRoleArn which is populated by the pipeline
- Add condition that can be used on resource based policies to determine whether or not to deploy a policy statement for the test role

Add test role parameter and condition

---

integration-tests/constants/requestData/webhookAPIRequestData.ts
package.json

- Run tests sequentially
- Recipient email and name should be used when creating valid data

Fix integration tests

---

template.yaml

Point at new SSM parameters to use the new shared infrastructure.

Update SSM parameter values to point at new shared data analysis infrastructure

---

README.md
esbuild.config.ts
template.yaml

* Update ESBuild config to build into different folders within `dist/`
* Update template so each function now has its own CodeUri property, and update handler path to match what ESBuild does

Remove unused lamba code from each package

---

template.yaml

Increase initiate athena query lambda memory size

---

.github/dependabot.yaml

Change dependency update schedule to monthly
Add custom label to version update PRs
Increase Dependabot PR limit to 10

Reduce noise from Dependabot

---

src/sharedServices/s3/checkS3BucketData.test.ts
src/sharedServices/s3/checkS3BucketData.ts

We had a bug with our previous implementation, whereby even when a file had completely finished restoring from Glacier, we didn't detect it, because the returned StorageClass is still set to Glacier (and the assumption was that the storage class would change: this turned out not to be the case).
Instead, we needed to pass in another parameter to the ListObjects command, which will return the restore status, and then we needed to check this restore status to determine whether or not the process had completed

Fix problem with Glacier restore check status

---

sonar-project.properties
src/lambdas/initiateDataRequest/validateZendeskRequest.ts
src/lambdas/initiateDataRequest/zendeskTicketDiffersFromRequest.ts

- **Ticket Number**: [TT2-1518](https://govukverify.atlassian.net/browse/TT2-1518) :ticket:
Updated regex to remove vulnerability to denial of service by using backtracking.
- added testConstants to sonar exclude as it is only used for the unit tests.
- refactored function to remove cognitive complexity
- amended sort method to remove sonarcloud issue
Changes pass unit tests:
All security hotspots removed from SonarCloud for this repo:
All issues addressed:
Passes Quality gate score:
After discussion, the regex changes where reverted and marked as `Safe` manually through the sonarCloud console.
[TT2-1518]: https://govukverify.atlassian.net/browse/TT2-1518?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

TT2-1518 | Sonarcloud issues and hotspots

---

sonar-project.properties
src/lambdas/initiateDataRequest/validateZendeskRequest.ts
src/lambdas/initiateDataRequest/zendeskTicketDiffersFromRequest.ts

This reverts commit c11ed0a093d51b50fc33a3c3e9b4de40bcb77d7a.
Reverting changes to see if thats causing tests to fail in Staging

Revert "TT2-1518 | Sonarcloud issues and hotspots (#429)"

---

sonar-project.properties
src/lambdas/initiateDataRequest/validateZendeskRequest.ts
src/lambdas/initiateDataRequest/zendeskTicketDiffersFromRequest.ts

This reverts commit de20c623372769d740b4f57d613ac1e337e8b45d.

Adding back TT2-1518 | Sonarcloud issues and hotspots (#429)

---

template.yaml

- **Ticket Number**: #[Your Ticket Number] :ticket:
- **Documentation Link(s)**: [:books: Does this relate to an ADR/RFC/Spike ticket?]
[Provide a brief but clear description of the changes made in this pull request. Explain why these changes are necessary and how they address the issue or feature request.]
- [List the specific changes made in bullet points. Be as detailed as necessary.]
[Provide step-by-step instructions for testing the changes made in this pull request. Were there any tests you weren't able to include but would have liked to? ]
[Include any screenshots or visual representations of the changes. Delete this section if not applicable.]
- [List any related pull requests that need to be reviewed or merged alongside this one.]
- [Please provide proper documentation or update …

TT2-1863: Adding alias to all the lambdas

---

open-api-specification.yaml

- **Ticket Number**: #[Your Ticket Number] :ticket:
Adding alias live to the function arn

TT2-1863: Adding alias to the arn in spec file

---

template.yaml

https://govukverify.atlassian.net/browse/TT2-1911
add ms timestamp to aws glue

TT2-1911 - add ms timestamp to glue

---

scripts/sendQueryResults/sendSQSMessageToCompletedQueue.test.ts
scripts/sendQueryResults/sendSQSMessageToCompletedQueue.ts

- Use AWS SDK to get queue URL from name and pass to sendSqsMessage

Queue URL Fix

---

template.yaml

Ticket Number: [DPT-812](https://govukverify.atlassian.net/browse/DPT-812)  🎫
Documentation Link(s): https://docs.google.com/spreadsheets/d/1aRj_TGJNW5cNgNggArOr_nh6jJZimk8aciBDY8D7mlY/edit?gid=1067175787#gid=1067175787 :books:
💡 Description
Now that FMS migration has been done in all environments and enough time has passed to show it is all working, we can remove our own WAFs and WAF-related resources
✨ Changes Made
- Remove WAF association and condition
[DPT-812]: https://govukverify.atlassian.net/browse/DPT-812?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DPT-812 Remove our own WAFs post FMS migration

---

scripts/utils/dateUtils.test.ts
scripts/utils/dateUtils.ts

Add date range validation to retrieve-audit-data to prevent input of incorrect date ranges

Add date range validation to retrieve-audit-data

---

template.yaml

- **Ticket Number**: https://govukverify.atlassian.net/browse/DPT-121
Update lambda node version to 22

SET-121: Update to node 22

---

template.yaml

- **Ticket Number**: https://govukverify.atlassian.net/browse/DPT-2023
This is to fix the DT layer to a hardcoded version

fixed layers to hardcoded DT arn

---

template.yaml

- **Ticket Number**: https://govukverify.atlassian.net/browse/DPT-2137
Fix a syntax error in the CloudWatch subscription filters

Dpt 2137 log filters

---

template.yaml

- **Ticket Number**: https://govukverify.atlassian.net/browse/DPT-2137
Removes the log filters from the api gateway log group

DPT-2137 Don't filter logs for the zendesk API gateway
